{{ $root := . -}}
{{- range $key, $value := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "secrets.labels" $root | nindent 4 }}
  name: {{ include "secrets.fullname" $root }}-{{ $key }}
data:
{{- range $innerKey, $innerValue := $value }}
{{ $innerKey | indent 2 }}: {{ $innerValue | b64enc | quote }}
{{- end }}
{{- end }}
