repositories:
  # - name: stable
  #   url: https://kubernetes-charts.storage.googleapis.com
  # - name: jetstack
  #   url: https://charts.jetstack.io
  # - name: appscode
  #   url: https://charts.appscode.com/stable/
  # - name: billimek
  #   url: https://billimek.com/billimek-charts/
  # - name: halkeye
  #   url: https://halkeye.github.io/helm-charts/
  # - name: ianduffy
  #   url: https://imduffy15.github.io/charts
  # - name: bitnami
  #   url: https://charts.bitnami.com/bitnami
  # - name: ingress-nginx
  #   url: https://kubernetes.github.io/ingress-nginx
  # - name: prometheus-community
  #   url: https://prometheus-community.github.io/helm-charts
  # - name: k8s-at-home
  #   url: https://k8s-at-home.com/charts/

templates:
  default: &default
    missingFileHandler: Warn
    values:
    - config/{{`{{ .Release.Name }}`}}/values.yaml
    - config/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    - config/{{`{{ .Release.Name }}`}}/values.yaml.gotmpl
    - config/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml.gotmpl
    secrets:
    - secrets/{{`{{ .Release.Name }}`}}/secrets.yaml
    - secrets/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}-secrets.yaml
    - secrets/{{`{{ .Release.Name }}`}}/secrets.yaml.gotmpl
    - secrets/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}-secrets.yaml.gotmpl

releases:
  - name: kubed
    namespace: kube-system
    chart: appscode/kubed
    version: 0.12.0
    <<: *default
  - name: external-dns
    namespace: kube-system
    chart: bitnami/external-dns
    version: 3.2.5
    <<: *default
  - name: nginx-ingress-tmp
    namespace: kube-system
    chart: ingress-nginx/ingress-nginx
    version: 3.1.0
    <<: *default
  - name: nginx-ingress-dmz
    namespace: kube-system
    chart: ingress-nginx/ingress-nginx
    version: 3.1.0
    <<: *default
  - name: nginx-ingress-dmz-redirect
    namespace: kube-system
    chart: ingress-nginx/ingress-nginx
    version: 3.1.0
    <<: *default
  - name: nginx-ingress-management
    namespace: kube-system
    chart: ingress-nginx/ingress-nginx
    version: 3.1.0
    <<: *default
  - name: nginx-ingress-main
    namespace: kube-system
    chart: ingress-nginx/ingress-nginx
    version: 3.1.0
    <<: *default
  - name: nginx-ingress-iot
    namespace: kube-system
    chart: ingress-nginx/ingress-nginx
    version: 3.1.0
    <<: *default
  - name: nginx-ingress-lot
    namespace: kube-system
    chart: ingress-nginx/ingress-nginx
    version: 3.1.0
    <<: *default
  - name: nginx-ingress-guest
    namespace: kube-system
    chart: ingress-nginx/ingress-nginx
    version: 3.1.0
    <<: *default
  - name: cert-manager
    namespace: kube-system
    chart: jetstack/cert-manager
    version: 1.0.3
    wait: true
    force: true
    atomic: true
    recreatePods: true
    <<: *default
  - name: metallb
    namespace: kube-system
    chart: stable/metallb
    version: 0.12.0
    <<: *default
  - name: prometheus-operator
    namespace: kube-system
    chart: prometheus-community/kube-prometheus-stack
    version: 9.4.3
    <<: *default
  - name: home-assistant
    namespace: default
    chart: ianduffy/home-assistant
    version: 1.0.3
    <<: *default
  - name: mosquitto
    namespace: default
    chart: ianduffy/mosquitto
    version: 0.0.6
    <<: *default
  - name: tasmoadmin
    namespace: default
    chart: ianduffy/tasmoadmin
    version: 0.0.1
    <<: *default
  - name: powerdns
    namespace: default
    chart: ianduffy/powerdns
    version: 0.0.2
    <<: *default
  # - name: tvheadend
  #   namespace: default
  #   chart: ianduffy/generic
  #   version: 0.0.7
  #   <<: *default
  # - name: spc-web-gateway
  #   namespace: default
  #   chart: ianduffy/generic
  #   version: 0.0.7
  #   <<: *default
  - name: imgproxy
    namespace: default
    chart: ianduffy/imgproxy
    version: 0.5.9
    <<: *default
  - name: unifi
    namespace: default
    chart: k8s-at-home/unifi
    version: 1.0.0
    <<: *default
  - name: secrets
    namespace: default
    chart: ./charts/secrets
    <<: *default
  - name: docker-registry
    namespace: default
    chart: stable/docker-registry
    <<: *default
  - name: certificates
    namespace: shared
    chart: ./charts/certificates
    wait: true
    force: true
    atomic: true
    recreatePods: true
    needs:
      - kube-system/cert-manager
    hooks:
      - events: ["prepare"]
        command: "sh"
        args: ["-c", "kubectl create namespace shared || true"]
    <<: *default

