apiVersion: v1
kind: Service
metadata:
  labels: {{ include "externalService.labels" . | nindent 4 }}
  name: {{ include "externalService.fullname" . }}
spec:
  type: ExternalName
  externalName: {{ .Values.externalName }}
  ports:
    - port: {{ .Values.externalPort }}
