apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "certificates.labels" . | nindent 4 }}
  name: {{ include "certificates.fullname" . }}
data:
{{ range $key, $value := .Values.secrets }}
{{ $key | indent 2 }}: {{ $value | b64enc | quote }}
{{ end }}
