{{- $root := . -}}
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "generic.fullname" . -}}
{{- range $index, $value := .Values.services }}
{{- if $value.ports.http -}}
---
{{- $servicePort := $value.ports.http -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "generic.labels" $root | indent 4 }}
{{- with $root.Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if $root.Values.ingress.tls }}
  tls:
  {{- range $root.Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range $root.Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-{{ $index }}
              servicePort: {{ $servicePort }}
  {{- end }}
{{- end }}
{{- end -}}
{{- end -}}