{{- $root := . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
{{ include "generic.labels" . | indent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{- if not $value.b64encoded }}
    {{ $key }}: {{ $value.data | b64enc | quote }}
  {{- else }}
    {{ $key }}: {{ $value.data }}
  {{- end }}
{{- end }}
