{{- $root := . -}}
{{ range $index, $value := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic.fullname" $root }}-{{ $index }}
{{- if $value.annotations }}
  annotations:
  {{- range $annotationName, $annotationValue := $value.annotations }}
    {{ $annotationName }}: {{ $annotationValue | quote }}
  {{- end }}
{{- end }}
  labels:
{{ include "generic.labels" $root | indent 4 }}
spec:
  type: {{ $value.type }}
  loadBalancerIP: {{ $value.address }}
  ports:
    {{- range $portName, $portNumber := $value.ports }}
    - port: {{ $portNumber }}
      targetPort: {{ index $value.targetPorts $portName }}
      {{- if $value.protocol }}
      protocol: {{ index $value.protocol $portName | default "TCP" }}
      {{- else }}
      protocol: TCP
      {{- end }}
      name: {{ $portName }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "generic.name" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
{{- end }}
