{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "tasmoadmin.serviceAccountName" . }}
  labels:
{{ include "tasmoadmin.labels" . | indent 4 }}
{{- end -}}
