apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns.fullname" . }}-tcp
{{- if .Values.dnsService.annotations }}
  annotations:
  {{- range $key, $value := .Values.dnsService.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.dnsService.dnsTcpAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
{{ include "powerdns.labels" . | indent 4 }}
spec:
  type: {{ .Values.dnsService.type }}
  loadBalancerIP: {{ .Values.dnsService.address }}
  ports:
    - port: {{ .Values.dnsService.ports.dnstcp }}
      targetPort: {{ .Values.dnsService.targetPorts.dnstcp }}
      protocol: {{ .Values.dnsService.protocol.dnstcp | default "TCP" }}
      name: dnstcp
  selector:
    app.kubernetes.io/name: {{ include "powerdns.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
