apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
{{ include "mosquitto.labels" . | indent 4 }}
data:
  "options.json": |-
{{ .Values.config | toJson | trimSuffix "\n" | indent 4 }}  
