{{- $root := . -}}
---
{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
{{ include "mosquitto.labels" . | indent 4 }}
type: Opaque
data:
{{ range $key, $value := .Values.certs }}
  {{ get $root.Values.config $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
