image:
  tag: latest-dev
env:
  DEBUG: "zigbee-herdsman*"
config:
  homeassistant: true

  serial:
    adapter: deconz

  advanced:
    log_level: debug
    channel: 15

additionalVolumeMounts:
  - name: usb
    mountPath: /dev/ttyACM0
additionalVolumes:
  - name: usb
    hostPath:
      path: /dev/ttyACM0

persistence:
  data:
    enabled: true
    emptyDir: false
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 5Gi