{{- if and .Values.ingress.enabled .Values.ingress.health.whitelist -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "imgproxy.fullname" . }}-health
  labels:
    app: {{ template "imgproxy.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.ingress.health.whitelist }}
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "imgproxy.fullname" .)) | quote }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /health
        backend:
          serviceName: {{ template "imgproxy.fullname" . }}
          servicePort: 80
{{- end -}}
