apiVersion: v1
kind: Service
metadata:
  name: {{ template "imgproxy.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ .Release.Name | quote }}
{{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  selector:
    app: {{ template "imgproxy.fullname" . }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 8081
    protocol: TCP
    targetPort: 8081
  type: {{ default "ClusterIP" .Values.service.type }}
{{- if .Values.service.address }}
  loadBalancerIP: {{ .Values.service.address }}
{{- end }}